sonar.projectKey=Danial-Afiq_tech-advisor
sonar.organization=danial-afiq

sonar.sources=backend/src/main,frontend/src
sonar.java.binaries=backend/target/classes

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true